name: AdminPanel
version: '${project.version}'
main: controllpanel.adminpanel.AdminPanel
api-version: 1.16
authors: [ 4e1owek ]
description: Panel with features that simplify server management
website: https://vk.com/wedbeepu_nk
commands:
  getposition:
    usage: /<command> <player>
    permission: permission.OnlyOp
    permission-message: "You do not have permission to use this command"
  lightning:
    usage: /<command> <player|@a> <Number of strokes>
    permission: permission.OnlyOp
    permission-message: "You do not have permission to use this command"
permissions :
  permission.OnlyOp:
    description: "OP"
    default: op